### ISSUE TITLE
viol unvioling files?

### ISSUE THREAD

**Issue by EZCLAP03** [5IGI0CP/libviol#1]
the heck does violing and unvioling files mean?

**Comment by 5IGI0** [comment]
![Screenshot from 2020-08-09 12-38-25](https://user-images.githubusercontent.com/52593687/89730231-4a24b000-da3d-11ea-8c6d-f2b8641f19af.png)

**Comment by tripulse** [comment]
@EZCLAP03 to understand this concept properly read the violeur theory, which is available in Trilounge's #5igi0-lab.

### Inshort
A *fille* is a violable object.
*libviol* is a violeur object, that can viol a *violable* object.

**Comment by tripulse** [comment]
That channel isn't available anymore, as said in **#notes** that is was axed.
